### PR TITLE
feat: fast miri for PRs

### PR DESCRIPTION
**Pull request by nelson137**
Only run Miri with 1 seed on PRs, but also run Miri on pushes to `main` with 8 seeds.

I don't have much experience with GitHub actions but this seems to work.

- I PRed this on my fork and merged it.
- The push to main ran the Miri job with 8 seeds
    - The original job from `ci.yml` moved to a new `validation.yml` file which only runs on pushes to `main`.
- Then I opened another PR, which ran Miri with only 1 seed.
    - The job ran for 3m 35s, but most of the build artifacts were already cached.

The only issue I see with this is the caching part of the job. The yml sets up these keys:

```yml
          key: ci-miri-${{ matrix.config.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ci-miri-${{ matrix.config.target }}-
```

which are now duplicated to 2 different jobs in 2 completely different workflows. I don't know if that's a problem or not.

### CODE REVIEW

**Comment by MaxCWhitehead** [comment]
I don't think the caching should be an issue, but not 100%.

For some reason the merge status checks shows `📡 Miri tests Expected — Waiting for status to be reported ` but appears to not be running - wondering if it might have something to do with the fact that miri test was previously in workflow that was 'pull_request' and now is under one that is 'pull_request_target'? 

I think `pull_request_target` runs against the base commit of main, the merge target, without merge changes. Maybe we want miri tests to remain in workflow that uses `pull_request`?

@zicklag lmk if that doesn't sound right - I've also not gone super deep on github actions.

**Comment by zicklag** [comment]
So I removed the requirement for the Miri Checks to run for PRs, and after this is merged I can re-enable the check. GitHub is weird with the way that you set required jobs. They have to be merged and then you require them by name.

**Comment by nelson137** [comment]
@MaxCWhitehead 

> In order to protect public repositories for malicious users we run all pull request workflows raised from repository forks with a read-only token and no access to secrets.
This makes common workflows like labeling or commenting on pull requests very difficult.
>
> In order to solve this, we’ve added a new `pull_request_target` event, which behaves in an almost identical way to the `pull_request` event with the same set of filters and payload.
>
> However, instead of running against the workflow and code from the merge commit, the event runs against the workflow and code from the base of the pull request.

Well that's good to know

**Comment by MaxCWhitehead** [comment]
> @MaxCWhitehead
> 
> > In order to protect public repositories for malicious users we run all pull request workflows raised from repository forks with a read-only token and no access to secrets.
> > This makes common workflows like labeling or commenting on pull requests very difficult.
> > In order to solve this, we’ve added a new `pull_request_target` event, which behaves in an almost identical way to the `pull_request` event with the same set of filters and payload.
> > However, instead of running against the workflow and code from the merge commit, the event runs against the workflow and code from the base of the pull request.
> 
> Well that's good to know

Yeah I've gone down this rabbithole before on gitlab - but figuring out how you want CI to run with respect to merged code / source branch CI / target branch CI when you might require secrets involved or afraid of malicious CI, it gets complicated fast. Fortunately our use case is pretty simple.

**Comment by MaxCWhitehead** [comment]
> So I removed the requirement for the Miri Checks to run for PRs, and after this is merged I can re-enable the check. GitHub is weird with the way that you set required jobs. They have to be merged and then you require them by name.

Thanks, I couldn't find these settings and got confused.

**Review by zicklag — APPROVED** [review]

**Comment by nelson137** [comment]
Hm, it looks like the x86_64 correctness checks failed on the merge, but not here. The job looks weird, it seemed to just stop after it installed clippy?

**Comment by MaxCWhitehead** [comment]
re-adding to merge queue to see if fluke or happens again

**Comment by MaxCWhitehead** [comment]
Re-ran with debug logs (https://github.com/fishfolk/bones/actions/runs/11058467513/job/30784205088) not sure if related, but the cache seems to be downloading 4+Gb of data, before extracting. We might need to look into CI cache invalidation / more specific key?

**Comment by MaxCWhitehead** [comment]
Deleted that cache entry to see what happens - seems to hang when unpacking cache

**Comment by nelson137** [comment]
Oh it looked like that last one succeeded.

I wonder if this is related at all, but the cache key for Miri is `ci-miri--5d1669cd2e05b0ca4...`, for some reason the `matrix.config.target` didn't get interpolated ([here](https://github.com/fishfolk/bones/actions/caches?query=sort%3Asize-desc)).

**Comment by MaxCWhitehead** [comment]
The issue was for clippy job which has different key than miri, so not sure is related. Maybe because miri does not have two config targets (does not run for both wasm and non-wasm?)

Clippy succeeded after deleting cache (see attempt 2 vs 3 on the link I shared), new one is `ci-x86_64-unknown-linux-gnu-44e4edf19f70059a16e09770bd78f2aee101fd89a0ece9cf84b848d0d093d262` (1.7GB) - last version of cache before I deleted was 4.2GB.

is it possible the compressed 4.2gb extracted takes up too much space on our CI runner? just a wild guess - we might want to keep an eye on this. Going to kick off merge queue again, expecting it will succeed this time.

**Comment by zicklag** [comment]
> is it possible the compressed 4.2gb extracted takes up too much space on our CI runner?

Maybe... The cache is just to speed things up, but Rust build dirs do grow over time as you keep building, so we might need to just delete the cache whenever CI starts to fail or something. :man_shrugging: It's lasted a while up to this point it seems like.

**Pull request merged**
